"""added field for rooms

Revision ID: b3a28438c12a
Revises: a80d429daa44
Create Date: 2023-05-08 20:36:53.992027

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3a28438c12a"
down_revision = "a80d429daa44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cleared_rooms", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("current_room", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("current_room")
        batch_op.drop_column("cleared_rooms")

    # ### end Alembic commands ###
